/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-qeJR-2I7lE95-xivUA9ylWq-xqDLDgaWc7ntrukVmTzpW8U5pOxzc4h5QAgaMVItASOG5EJ3Y-WO5kr7sEGCf6cNTphyvz6Has8MOp-nIaALwiW6NxXvuPaf",
  "tt": "tt-1-e-d3ZLjw-oxp9l-nw8o6p8U4uIZcTX71uz-KFkeCG78=",
  "version": "2020-11-20"
}

export default ebconfig;